config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :workspaces do
    resources :equipment_types do
    end
  end
  resources :equipment_types, only: [:show] do
    resources :equipment_units do
    end
  end

  root to: 'admin/dashboard#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/equipment_type.rb
class EquipmentType < ApplicationRecord
  belongs_to :workspace
  has_many :equipment_units, dependent: :destroy
  has_many :maintenance_plans, dependent: :destroy

  validates_presence_of :name

  accepts_nested_attributes_for :maintenance_plans, allow_destroy: true
end

app/models/equipment_unit.rb
class EquipmentUnit < ApplicationRecord
  belongs_to :equipment_type
  has_many :maintenance_plans, through: :equipment_type

  validates_presence_of :name
  validates_presence_of :initial_hourmeter
  validates_presence_of :monthly_usage

  def max_yearly_usage
    @max_yearly_usage ||= initial_hourmeter + monthly_usage * 12
  end

  def maintenance_stops
    @maintenance_stops ||= SortedSet.new.tap do |stops|
      maintenance_plans.each do |plan|
        stops.merge maintenance_stops_for_plan(plan)
      end
    end.to_a
  end

  def all_monthly_budgets
    @all_monthly_budgets ||= Array.new.tap do |budget|
      current_usage = initial_hourmeter
      next_usage = current_usage + monthly_usage
      (1..12).each do |month|
        logger.info "Month #{month}"
        budget_for_month = []
        usage_range = [current_usage, next_usage - 1]

        stops_in_usage = maintenance_stops.find_all { |stop| stop.between?(*usage_range) }
        logger.info "Usage range: #{usage_range}"
        logger.info "Stops in usage: #{stops_in_usage}"

        stops_in_usage.each do |stop|
          logger.info "Analyzing stop #{stop}"
          plan_in_stop = maintenance_plans.order('interval DESC').find do |plan|
            maintenance_stops_for_plan(plan).include?(stop)
          end

          budget_for_month << {
            plan: plan_in_stop,
            stop: stop
          } if plan_in_stop

          logger.info "Found #{plan_in_stop.name} at #{stop}"
        end
        current_usage = next_usage
        next_usage += monthly_usage
        budget << budget_for_month
      end
    end
  end

  private

  def maintenance_stops_for_plan(plan)
    @maintenance_stops_for_plan ||= {}
    @maintenance_stops_for_plan["plan_#{plan.id}"] ||= SortedSet.new.tap do |stops|
      current_stop = (initial_hourmeter.to_f / plan.interval).ceil * plan.interval
      while current_stop <= max_yearly_usage do
        stops << current_stop
        current_stop += plan.interval
      end
    end.to_a
  end

end

app/models/maintenance_plan.rb
class MaintenancePlan < ApplicationRecord
  belongs_to :equipment_type

  validates_presence_of(:name)
  validates_presence_of(:cost)
  validates_presence_of(:interval)
  validates_numericality_of(:cost)
  validates_numericality_of(:interval, only_integer: true)
end

app/models/workspace.rb
class Workspace < ApplicationRecord
  has_many :equipment_types, dependent: :destroy
  has_many :equipment_units, through: :equipment_types

  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/workspaces/budget_by_equipment_type.html.erb
<table class="index_table">
  <thead>
  <tr>
    <th>Equipment Type</th>
    <% (1..12).each do |month| %>
      <th><%= Date::MONTHNAMES[month] %></th>
    <% end %>
  </th>
  </thead>
  <% @presenter.output.each do |type| %>
    <tr>
      <td>
        <%= link_to type[:name], admin_workspace_equipment_type_path(@workspace, type[:id]) %>
      </td>
      <% (1..12).each do |month| %>
        <td>
          <%= number_to_currency(type[:budget_per_month][month - 1]) %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>
<div id="index_footer">
  <div class="download_links">
    <span>Download:</span>
    <%= link_to 'CSV', budget_by_equipment_type_admin_workspace_path(@presenter.workspace, format: 'csv') %>
  </div>
</div>

app/views/admin/workspaces/budget_by_equipment_unit.html.erb
<table class="index_table">
  <thead>
  <tr>
    <th>Equipment Name</th>
    <% (1..12).each do |month| %>
      <th><%= Date::MONTHNAMES[month] %></th>
    <% end %>
  </th>
  </thead>
  <% @presenter.output.each do |unit| %>
    <tr>
      <td>
        <%= link_to unit[:name], admin_equipment_type_equipment_unit_path(unit[:equipment_type_id], unit[:id]) %>
      </td>
      <% (1..12).each do |month| %>
        <td>
          <%= number_to_currency(unit[:budget_per_month][month - 1]) %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>
<div id="index_footer">
  <div class="download_links">
    <span>Download:</span>
    <%= link_to 'CSV', budget_by_equipment_unit_admin_workspace_path(@presenter.workspace, format: 'csv') %>
  </div>
</div>

app/views/admin/workspaces/schedule_by_equipment_unit.html.erb
<table class="index_table">
  <thead>
  <tr>
    <th>Equipment Name</th>
    <% (1..12).each do |month| %>
      <th><%= Date::MONTHNAMES[month] %></th>
    <% end %>
  </th>
  </thead>
  <% @presenter.output.each do |unit| %>
    <tr>
      <td>
        <%= link_to unit[:name], admin_equipment_type_equipment_unit_path(unit[:equipment_type_id], unit[:id]) %>
      </td>
      <% unit[:all_monthly_budgets].each do |monthly_budget| %>
        <td>
          <ul>
            <% monthly_budget.each do |plan_with_stop| %>
              <li>
                <%= plan_with_stop[:plan].name %> at <%= plan_with_stop[:stop] %>
              </li>
            <% end %>
          </ul>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>
<div id="index_footer">
  <div class="download_links">
    <span>Download:</span>
    <%= link_to 'CSV', schedule_by_equipment_unit_admin_workspace_path(@presenter.workspace, format: 'csv') %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetOfMaintenance</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>